### ISSUE TITLE
Building on Apple Silicon

### ISSUE THREAD

**Issue by hugolundin** [SwiftGit2/SwiftGit2#182] opened 2020-12-01 12:15 UTC
Hi! I am working on a macOS app that uses SwiftGit2. I would like to work on it on my new Apple Silicon Mac, but cannot figure out how to build the library correctly. 

- Carthage finishes with `*** ARCHIVING FAILED ***`.
- Cloning and trying to build the macOS version with Xcode because of `ld: warning: ignoring file External/libgit2.a, building for macOS-x86_64 but attempting to link with file built for macOS-arm64`. 

Do anyone have a suggestion on how to proceed? I guess I should be able to build `libgit2` manually for ARM and then replace `External/libgit2.a` before building the Xcode project. Is there any official way to do it right now? I don't care if I have to use the library with Rosetta or similar. 

Thank you!

**Comment by twa16** [comment] 2020-12-17 15:45
@hugolundin Is this still an issue with the new merged PR on master? #183

**Comment by penso** [comment] 2021-01-07 09:55
@twa16 Just tried on `master` and I have the same failure

**Comment by penso** [comment] 2021-01-07 09:56
Using Carthage I get:

```
ld: warning: ignoring file External/libgit2.a, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file External/libcrypto.a, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/lib/libssh2.a, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file External/libssl.a, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
Undefined symbols for architecture arm64:
(...)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by twa16** [comment] 2021-01-08 03:39
Awesome thank you @penso . I have been working through the M1 issues on my Mac so I expect a fix in the coming weeks.

To any others that stumble upon this: there seem to be a few possible places the build will get stuck depending on what fixes you try. The issue is being worked.

**Comment by joehinkle11** [comment] 2021-01-08 14:32
@twa16 I had the same problems last weekend. I can help you with this issue

**Comment by twa16** [comment] 2021-01-09 21:45
@joehinkle11 Awesome. Do you have a patched up version of the source tree somewhere? We can compare notes.

**Comment by joehinkle11** [comment] 2021-01-09 23:42
@twa16 I got it working! I just prebuilt libgit2 , openssl, and libssh2 on my intel Mac, and then airdropped the `External` to my M1. Works like that for device builds. For simulator builds, you just add a build setting. Screenshot below

<img width="932" alt="image" src="https://user-images.githubusercontent.com/8505851/104110906-44601e80-52aa-11eb-9520-3c598f75840c.png">

A true solution would be to fix the build scripts used to build libgit2 , openssl, and libssh2. That would make swifgit2 way more accessible

**Comment by joehinkle11** [comment] 2021-01-09 23:47
Also, this is the External folder I referred to above

![image](https://user-images.githubusercontent.com/8505851/104110948-d9631780-52aa-11eb-8249-86e486f82314.png)

I don't have a repo up for this, but I'm working with @brandonplank on "SwiftGit3" https://github.com/brandonplank/SwiftGit3 and will add full M1 support there if I find a solution. But I have no idea how to fix those build scripts...and I don't have time to put a lot of effort into it

**Comment by joehinkle11** [comment] 2021-05-07 16:05
My "SwiftGit3" fork builds on silicon via SPM https://github.com/App-Maker-Software/SwiftGit3

**Comment by hannesa2** [comment] 2024-11-19 08:37
The CI can now build arm64 as well https://github.com/SwiftGit2/SwiftGit2/actions/runs/11907258039/job/33180656216?pr=212

<img width="327" alt="image" src="https://github.com/user-attachments/assets/5e027875-a30d-49e7-a9c9-b1618a97b3bc">

**Closed** 2024-11-19 14:06 UTC
